server:
  port: 89
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
      enabled: true

  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    time-between-eviction-runs-millis: 30000
#    min-evictable-idle-time-millis: 300000
#    test-while-idle: true
#    test-on-borrow: false
#    test-on-return: false
#    filters: stat
#    break-after-acquire-failure: true
#    connection-error-retry-attempts: 3
    validation-query: SELECT 1
    erp:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/erp_yto?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
    test:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/test?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
      username: root
      password: root
    sqlserver-back:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://DESKTOP-SQ3J3GR\SQLEXPRESS;DatabaseName=AIS001;integratedSecurity=true;
      username: DESKTOP-SQ3J3GR\\86152
    sqlserver-kd:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://DESKTOP-SQ3J3GR\SQLEXPRESS;DatabaseName=AISBACK;integratedSecurity=true;
      username: DESKTOP-SQ3J3GR\\86152

#  datasource:
##    type: com.alibaba.druid.pool.DruidDataSource
##    time-between-eviction-runs-millis: 30000
##    min-evictable-idle-time-millis: 300000
##    test-while-idle: true
##    test-on-borrow: false
##    test-on-return: false
##    filters: stat
##    break-after-acquire-failure: true
##    connection-error-retry-attempts: 3
#    validation-query: SELECT 1
#    erp:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3307/erp_yto?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#      username: root
#      password: root
#    test:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://KDSERVER;DatabaseName=AIS20201103111830;integratedSecurity=true;
#      username: sa
#      password: kd@888888
#    sqlserver-back:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://KDSERVER;DatabaseName=AIS20201103111830;integratedSecurity=true;
#      username: sa
#      password: kd@888888
#    sqlserver-kd:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://KDSERVER;DatabaseName=AIS20201103111830;integratedSecurity=true;
#      username: sa
#      password: kd@888888

    config:
      location: classpath:/
      additional-location: file:${DEMO_HOME}/config/
      name: application

  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/

  mvc:
    static-path-pattern: /**


  thymeleaf:
    mode: HTML5
    cache: true
    prefix: classpath:/
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    template-resolver-order: 1

  logging:
    config: file:${DEMO_HOME}/config/logback.xml

mybatis:
  mapper-locations:  classpath:mybatis/**/*Mapper.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: cn.com.yhb.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

  resources:
    static-locations: classpath:/static/

  mvc:
    static-path-pattern: /**

schedule:
  data:
    switch: true