file:
  #web_resources: classpath:/resources/templates/
  web_resources: classpath:/resources/static/
  ##download_path: ${DEMO_HOME}/download/

server:
  port: 88
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
      enabled: true

  config:
    location: classpath:/
    additional-location: file:${DEMO_HOME}/config/
    name: application

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    time-between-eviction-runs-millis: 30000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat
    break-after-acquire-failure: true
    connection-error-retry-attempts: 3
    validation-query: SELECT 1
  #    validation-query: SELECT 1 from dual
    test:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/test?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
      username: root
      password: root
    test1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/test1?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
      username: root
      password: root

  resources:
    #static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/ecms/
    static-locations: classpath:/META-INF/resources/, classpath:/static/ecms/

  mvc:
    static-path-pattern: /**


  thymeleaf:
    mode: HTML5
    cache: true
    #prefix: classpath:/templates/
    prefix: classpath:/static/ecms/
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    template-resolver-order: 1

  logging:
    config: file:${DEMO_HOME}/config/logback.xml

mybatis:
  mapper-locations: classpath:mybatis/mapper/ds1/**/*Mapper.xml, classpath:mybatis/mapper/ds2/**/*Mapper.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: cn.com.yhb.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

  resources:
    static-locations: classpath:/static/

  mvc:
    static-path-pattern: /**

